### ISSUE TITLE
Query parameter used instead of body for Reframe requests

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-delegated-routing#22]
Is this a holdover from before we merged the Reframe spec?

https://github.com/ipfs/go-delegated-routing/blob/3729ba353037ef1c0d40ba1e87b352acda9c7283/gen/proto/proto_edelweiss.go#L1620

The spec indicates this should be in the body of the POST request (cc @lidel I think this was your suggestion when we did the spec change).
https://github.com/ipfs/specs/blob/6bdb7b2751038e1d0212a40494ea8fd4018f384c/REFRAME.md?plain=1#L46

**Comment by petar** [comment]
It looks like it. I'll start a PR.

**Comment by lidel** [comment]
@aschmahmann @petar  query should be removed :+1:  but we may want to support  `GET` for improved HTTP caching – see proposal in https://github.com/ipfs/specs/pull/287

**Comment by petar** [comment]
@thattommyhall @willscott FYI, I made a change to Reframe implementation which moves the query parameters from the URL to the HTTP body to follow the Reframe spec more closely (this issue). As a result, we'll have to redeploy the hydra-indexer connection, after the Hydra (https://github.com/libp2p/hydra-booster/pull/170) and Indexer (https://github.com/filecoin-project/storetheindex/pull/563) update PRs are merged.

**Comment by petar** [comment]
This feature is implemented and merged. We will wait on redeploying until the https://github.com/ipfs/specs/issues/282 is also resolved. Closing this issue here as done.
