### ISSUE TITLE
Add cacheable GET endpoint for findProviders

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-delegated-routing#27]
## Done Criteria
The implementation supports the latest reframe spec in https://github.com/ipfs/specs/pull/287

## Why Important
See https://github.com/ipfs/specs/pull/287

**Comment by BigLep** [comment]
Related Edelweiss change: https://github.com/ipld/edelweiss/pull/48

**Comment by guseggert** [comment]
done: https://github.com/ipfs/go-delegated-routing/commit/30ca77f67baddf32e1fd95e685e7186449d88089
