### ISSUE TITLE
Method `proto.DelegatedRouting_Client.GetIPNS` is never used.

### ISSUE THREAD

**Issue by ajnavarro** [ipfs/go-delegated-routing#30]
Client implementation uses `GetIPNSAsync` for `GetIPNS`.

**Comment by BigLep** [comment]
@ajnavarro : I'm confused.  What is the done criteria for this issue?  I assume we're removing something?  Lets please specify that.

**Comment by ajnavarro** [comment]
Actually, I'm not sure. I would say to use `DelegatedRouting_Client.GetIPNS` instead of `DelegatedRouting_Client.GetIPNS_Async` will be the right approach, but maybe I'm missing something and it is done that way for a reason.

**Comment by ajnavarro** [comment]
Fix not needed.
