### ISSUE TITLE
code gen should format output file

### ISSUE THREAD

**Issue by willscott** [ipfs/go-delegated-routing#38]
when going into `gen/` and running `go run .` to re-recreate the `gen/proto` directory, the resulting file is not properly `go fmt`'d.

There is not documentation or process that one additionally needs to manually run `go fmt gen/proto/*.go` afterwards.

a subsequent PR will otherwise fail CI with:
```
All: gen/proto/proto_edelweiss.go#L1
File is not gofmt-ed.
```

**Comment by guseggert** [comment]
done as part of https://github.com/ipfs/go-delegated-routing/commit/ae73effad7f18dc7a2409e3d070139c968bee542
