### ISSUE TITLE
Enable easy extension of provider records in API

### ISSUE THREAD

**Issue by petar** [ipfs/go-delegated-routing#5]
We need to enable an easy programming pattern for extending the provider records returned by calls to GetP2PProviders, in order to enable Indexers to reuse their delegated routing endpoint for other purposes.

## Problem:

We currently define data types in Go and use their default JSON encoding as wire format.
We manually make sure that the resulting JSON is DAGJSON-compatible.
This is error prone if changes to the data structures are to be made frequently.

## Potential solution:

Use IPLD schema to generate serialization code and Go data structures.

## Acceptance criteria:

Straightforward method for adding fields to protocol data types.

**Comment by BigLep** [comment]
2022-01-04 discussion:
- [ ]  Merge bindnode PR: https://github.com/ipld/go-ipldtool/pull/3
- [ ] Rewrite delegated routing to use bindnode compiler

**Comment by BigLep** [comment]
2022-02-08 discussion: 
1. Update provider records - solved by moving delegated routing to IPLD schema: https://github.com/ipfs/go-delegated-routing/pull/6
2. Passthrough requirement - will be handled by Protocol Compiler: https://github.com/ipfs/go-delegated-routing/issues/9

We're closing this issue as a result.
