### ISSUE TITLE
Determine v1 schema

### ISSUE THREAD

**Issue by petar** [ipfs/go-delegated-routing#8]
## Done Criteria
[There is a schema](https://github.com/ipfs/go-delegated-routing/blob/ipld/ipld/routing.ipldsch) that Go IPFS Stewards (go-ipfs) and Data Systems (storethesytem) agree on and is checked in.  Basically, with what we know today, are there any changes that should be made to the schema?  If so, they should get be checked in. 

## Why Important
Enables client and server implementations to be worked on and deployed independently without fear that there will be breaking changes.  This is needed for https://github.com/ipfs/go-ipfs/issues/8775.

## Notes
This v1 schema should be set in light of what have learned from delegated routing conversations with storetheindex.  The schema should be set based on what is believed to be best for delegated-routing, but should be informed of real usecases.

As part of this discussion, we should be clear about where the "Filecoin records" are getting filtered out: a) on the Indexer implementation of "findproviders" or b) on the client side (e.g., Hydra, go-ipfs) after getting the "findproviders" result.

There are existing / related PRs open around this:
#6 
#7

**Comment by willscott** [comment]
I left my comments in https://github.com/ipfs/go-delegated-routing/pull/6 a bit ago, but the main things I'd like to see in the shared schema are:
* extended / additional struct defining filecoin graphsync as an additional protocol to bitswap
* potentially a way in `GetP2PProvideRequest` for requests to specify which protocols they support.
    * The most natural options from my perspective at a protocol level are that either the client will request with a list of supported protocols and get back relevant (filtered) records, or the client will get back all records and filter them locally.

**Comment by BigLep** [comment]
I don't know yet when we'll pick this up.  We're working on getting input from leadership on where we should focus.  I am aiming to have more clarity on this by end of week (2022-03-11).

**Comment by BigLep** [comment]
2022-03-22 conversation: this is being acted on now.  The plan is to write a ipfs/spec that will mostly be IPLD schema.

**Comment by aschmahmann** [comment]
Spec PR https://github.com/ipfs/specs/pull/272

**Comment by BigLep** [comment]
Resolving since https://github.com/ipfs/specs/pull/272 was merged.
