### ISSUE TITLE
Proposal for a protocol compiler

### ISSUE THREAD

**Issue by petar** [ipfs/go-delegated-routing#9]
There is a confluence between PL's pressing need for an RPC compiler and delegate routing's need for automatically enforcing protocol interoperability across teams and independent repos. This confluence naturally calls for a full-featured industry-grade protocol compiler, which has the features and maturity of Google's protobuf compiler.

- [x] proposal write-up: https://docs.google.com/document/d/1hkDJTcxC24ozdWZ0mrskJbKZf2s8P6a3RDWV51NNxNI/edit?usp=sharing
  - [ ] address questions and comments
- [ ] detailed package manager proposal
  - [ ] socialize and sign-off from stakeholders
- [ ] detailed type system proposal
  - [ ] socialize and sign-off from stakeholders

**Comment by BigLep** [comment]
Closing this as the larger effort is happening in https://github.com/ipld/edelweiss including the MVP issue here: https://github.com/ipld/edelweiss/issues/3
